ToDoList/ToDoList.WEB/Models/MissionViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ToDoList.WEB.Models
{
    public class MissionIndexView
    {
        [HiddenInput(DisplayValue = false)]
        public int MissionId { get; set; }
        [Required]
        [Display(Name = "Название задачи")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Описание")]
        public string Description { get; set; }
        [Display(Name = "Дата старта")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime MissionStart { get; set; }
        [Display(Name = "Дата окончания")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime MissionFinish { get; set; }
    }

    public class MissionEditView
    {
        [HiddenInput(DisplayValue = false)]
        public int MissionId { get; set; }
        [Required]
        [Display(Name = "Название задачи")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Длина строки от 2 букв до 50!")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Описание")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Длина строки от 2 букв до 50!")]
        public string Description { get; set; }
        [Display(Name = "Дата начала")]
        [Required(ErrorMessage = "Введите дату начала")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime MissionStart { get; set; }
        [Display(Name = "Дата окончания")]
        [Required(ErrorMessage = "Введите дату окончания")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime MissionFinish { get; set; }
    }

    public class MissionCreateView
    {
        [HiddenInput(DisplayValue = false)]
        public int MissionId { get; set; }
        [Required]
        [Display(Name = "Название задачи")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Длина строки от 2 букв до 50!")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Описание")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Длина строки от 2 букв до 50!")]
        public string Description { get; set; }
        [Display(Name = "Дата начала")]
        [Required(ErrorMessage = "Введите дату начала")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime MissionStart { get; set; }
        [Display(Name = "Дата окончания")]
        [Required(ErrorMessage = "Введите дату окончания")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime MissionFinish { get; set; }
    }
}

ToDoList/ToDoList.WEB/Controllers/MissionController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using ToDoList.Core;
using ToDoList.Entities.Models;
using ToDoList.WEB.Models;

namespace ToDoList.WEB.Controllers
{
    public class MissionController : Controller
    {
        private readonly IMissionRepo missionRepo;

        public MissionController(IMissionRepo repo)
        {
            missionRepo = repo;
        }
        public ViewResult Index()
        {
            return View();
        }

        public async Task<PartialViewResult> Load()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Mission, MissionIndexView>());
            var map = new Mapper(config);
            var missions = map.Map<List<MissionIndexView>>(await missionRepo.GetItems());

            return PartialView(missions);
        }
        [HttpGet]
        public async Task<PartialViewResult> Details(int id)
        {
            try
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<Mission, MissionIndexView>());
                var map = new Mapper(config);
                var mission = map.Map<Mission, MissionIndexView>(await missionRepo.GetById(id));

                return PartialView(mission);
            }
            catch
            {
                return PartialView("~/Views/Shared/Error.cshtml");
            }
        }

        public PartialViewResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> Create(MissionCreateView item)
        {
            try
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<MissionCreateView, Mission>());
                var map = new Mapper(config);
                var mission = map.Map<MissionCreateView, Mission>(item);

                await missionRepo.Insert(mission);

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = ex.Message });
            }
        }

        [HttpGet]
        public async Task<PartialViewResult> Edit(int id)
        {
            try
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<Mission, MissionEditView>());
                var map = new Mapper(config);
                var mission = map.Map<Mission, MissionEditView>(await missionRepo.GetById(id));

                return PartialView(mission);
            }
            catch
            {
                return PartialView("~/Views/Shared/Error.cshtml");
            }
        }

        [HttpPost]
        public async Task<JsonResult> Edit(MissionEditView item)
        {
            try
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<MissionEditView, Mission>());
                var map = new Mapper(config);
                var mission = map.Map<MissionEditView, Mission>(item);

                await missionRepo.Update(mission);

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            try
            {
                await missionRepo.Remove(id);

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = ex.Message });
            }
        }
    }
}

ToDoList/ToDoList.WEB/Views/Mission/Create.cshtml
@model ToDoList.WEB.Models.MissionCreateView

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="nameModalOperation" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit iformation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="editPurposeForm">
                    @using (Html.BeginForm())
                    {
                        <label id="serverError"></label>
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(m => m.MissionId)
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(m => m.Name)
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @type = "text", @placeholder = "Enter name" })
                            @Html.ValidationMessageFor(m => m.Name)
                        </div>
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(m => m.Description)
                            @Html.TextBoxFor(m => m.Description, new { @class = "form-control", @type = "text", @placeholder = "Enter description" })
                            @Html.ValidationMessageFor(m => m.Description)
                        </div>
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(m => m.MissionStart)
                            @Html.TextBoxFor(m => m.MissionStart, new { @class = "form-control", @type = "text", @placeholder = "Enter start date" })
                            @Html.ValidationMessageFor(m => m.MissionStart)
                        </div>
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(m => m.MissionFinish)
                            @Html.TextBoxFor(m => m.MissionFinish, new { @class = "form-control", @type = "text", @placeholder = "Enter finish date" })
                            @Html.ValidationMessageFor(m => m.MissionFinish)
                        </div>
                        <div class="modal-footer">
                            <input id="editePurposeBtn" type="submit" class="btn btn-success" value="Create" />
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#myModal').ready(() => {
        showCreateMission();
    })

    function showCreateMission() {
        $('#myModal').modal('show');
    }

    function hideCreateMission() {
        $('#myModal').modal('hide');
    }

    $('form').on('submit', function (event) {
        event.preventDefault();

        $.ajax({
            url: '@Url.Action("Create", "Mission")',
            type: 'POST',
            data: $('form').serialize(),
            success: function (result) {
                if (result.result) {
                    hideCreateMission();
                    load();
                }
                else {
                    alert("Невозможно добавить!");
                }
            }
        })
    })
</script>

ToDoList/ToDoList.WEB/Views/Mission/Details.cshtml
@model ToDoList.WEB.Models.MissionIndexView

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="nameModalOperation" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Information about purpose</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3><b>Name</b> : @Model.Name</h3>
                <h3><b>Descroption</b> : @Model.Description</h3>
                <h5><b>Date start</b> : @Model.MissionStart</h5>
                <h5><b>Date finish</b> : @Model.MissionFinish</h5>
            </div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#myModal').ready(() => {
        showDetailsForm();
    });

    function showDetailsForm() {
        $('#myModal').modal('show');
    }
</script>

ToDoList/ToDoList.WEB/Views/Mission/Edit.cshtml
@model ToDoList.WEB.Models.MissionEditView

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="nameModalOperation" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit iformation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="editPurposeForm">
                    @using (Html.BeginForm())
                    {
                        <label id="serverError"></label>
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(m => m.MissionId)
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(m => m.Name)
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @type = "text", @placeholder = "Enter name" })
                            @Html.ValidationMessageFor(m => m.Name)
                        </div>
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(m => m.Description)
                            @Html.TextBoxFor(m => m.Description, new { @class = "form-control", @type = "text", @placeholder = "Enter description" })
                            @Html.ValidationMessageFor(m => m.Description)
                        </div>
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(m => m.MissionStart)
                            @Html.TextBoxFor(m => m.MissionStart, new { @class = "form-control", @type = "text", @placeholder = "Enter start date" })
                            @Html.ValidationMessageFor(m => m.MissionStart)
                        </div>
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(m => m.MissionFinish)
                            @Html.TextBoxFor(m => m.MissionFinish, new { @class = "form-control", @type = "text", @placeholder = "Enter finish date" })
                            @Html.ValidationMessageFor(m => m.MissionFinish)
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="glyphicon glyphicon-erase btn btn-default" id="btnDelete"> Delete</button>
                            <input id="editePurposeBtn" type="submit" class="btn btn-success" value="Create" />
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="confirmModal" style="display: none; z-index: 1050;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" id="confirmMessage">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="confirmOk">Ok</button>
                <button type="button" class="btn btn-default" id="confirmCancel">Cancel</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#myModal').ready(() => {
        showMissionEdit();
    })

    function showMissionEdit() {
        $('#myModal').modal('show');
    }

    function hideMissionEdit() {
        $('#myModal').modal('hide');
    }

    $('form').on('submit', function (event) {
        event.preventDefault();

        $.ajax({
            url: '@Url.Action("Edit", "Mission")',
            type: 'POST',
            data: $('form').serialize(),
            success: function (result) {
                if (result.result) {
                    hideEditMission();
                    load();
                }
                else {
                    alert("Невозможно обновить!");
                }
            }
        })
    })

    var YOUR_MESSAGE_STRING_CONST = "Your confirm message?";

        $('#btnDelete').on('click', function (e) {
        confirmDialog(YOUR_MESSAGE_STRING_CONST, function () {

            $.ajax({
                url: '@Url.Action("Delete", "Mission")/' + @Model.MissionId,
                type: 'POST',
                success: function (result) {
                    if (result.result) {
                        load();
                    }
                    else {
                        alert('Невозможно удалить!');
                    }
                }
            })
        });
    });

    function confirmDialog(message, onConfirm) {
        hideMissionEdit();
        var fClose = function () {
            modal.modal("hide");
        };
        var modal = $("#confirmModal");
        modal.modal("show");
        $("#confirmMessage").empty().append(message);
        $("#confirmOk").unbind().one('click', onConfirm).one('click', fClose);
        $("#confirmCancel").unbind().one("click", function () {
            showMissionEdit();
            $('#confirmModal').modal('hide');
        });
    }
</script>

ToDoList/ToDoList.WEB/Views/Mission/Index.cshtml
@{
    ViewBag.Title = "Missions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Информация о задачах</h2>

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="spinner-border" role="status" id="loader">
            <span class="visually-hidden">Загрузка...</span>
        </div>
    </div>
</div>

<div id="lines">
    <div id="window"></div>
    <div id="windowModal"></div>
</div>

<script type="text/javascript">
    jQuery(function() {
        load();
    });

    function load() {
        $('#loader').css('display', 'display');
        console.log("aaaa");
        $('#window').load('@Url.Action("Load", "Mission")',
            function () {
                $('#loader').css('display', 'none');
            });
    }

    detailsMission = function (id) {
        $('#windowModal').load('@Url.Action("Details", "Mission")/' + id);
    }

    editMission = function (id) {
        $('#windowModal').load('@Url.Action("Edit", "Mission")/' + id);
    }

    createMission =  function () {
        $('#windowModal').load('@Url.Action("Create", "Mission")');
    }
</script>

ToDoList/ToDoList.WEB/Views/Mission/Load.cshtml
@model IEnumerable<ToDoList.WEB.Models.MissionIndexView>

<a href="#" class="btn btn-outline-primary" onclick="return createMission()">Create</a>

@if (Model.Count() > 0)
{
    <table class="table table-bordered border-primary">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Date</th>
                <th>Function</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.MissionId</th>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @item.MissionStart.ToShortDateString() - @item.MissionFinish.ToShortDateString()
                    </td>
                    <td>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                            <h6><a href="#" class="btn btn-outline-primary" onclick="return detailsMission(@item.MissionId)">Details</a></h6>
                            <h6><a href="#" class="btn btn-outline-primary" onclick="return editMission(@item.MissionId)">Edit</a></h6>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>Нет данных!</h3>
}