ToDoList/ToDoList.WEB/Controllers/PurposeController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using ToDoList.Core;
using ToDoList.Entities.Models;
using ToDoList.WEB.Models;

namespace ToDoList.WEB.Controllers
{
    public class PurposeController : Controller
    {
        private readonly IPurposeRepo purposeRepo;

        public PurposeController(IPurposeRepo repo)
        {
            purposeRepo = repo;
        }

        public ViewResult Index()
        {
            return View();
        }

        public async Task<PartialViewResult> Load()
        {
            var config = new MapperConfiguration(cfg => cfg.CreateMap<Purpose, PurposeIndexView>());
            var map = new Mapper(config);
            var purposes = map.Map<List<PurposeIndexView>>(await purposeRepo.GetItems());

            return PartialView(purposes);
        }
        [HttpGet]
        public async Task<PartialViewResult> Details(int id)
        {
            try
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<Purpose, PurposeIndexView>());
                var map = new Mapper(config);
                var purpose = map.Map<Purpose, PurposeIndexView>(await purposeRepo.GetById(id));

                return PartialView(purpose);
            }
            catch
            {
                return PartialView("~/Views/Shared/Error.cshtml");
            }
        }

        public PartialViewResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> Create(PurposeCreateView item)
        {
            try
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<PurposeCreateView, Purpose>());
                var map = new Mapper(config);
                var purpose = map.Map<PurposeCreateView, Purpose>(item);

                await purposeRepo.Insert(purpose);

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = ex.Message });
            }
        }

        [HttpGet]
        public async Task<PartialViewResult> Edit(int id)
        {
            try
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<Purpose, PurposeEditView>());
                var map = new Mapper(config);
                var purpose = map.Map<Purpose, PurposeEditView>(await purposeRepo.GetById(id));

                return PartialView(purpose);
            }
            catch
            {
                return PartialView("~/Views/Shared/Error.cshtml");
            }
        }

        [HttpPost]
        public async Task<JsonResult> Edit(PurposeEditView item)
        {
            try
            {
                var config = new MapperConfiguration(cfg => cfg.CreateMap<PurposeEditView, Purpose>());
                var map = new Mapper(config);
                var purpose = map.Map<PurposeEditView, Purpose>(item);

                await purposeRepo.Update(purpose);

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = ex.Message });
            }
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            try
            {
                await purposeRepo.Remove(id);

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(new { result = false, message = ex.Message });
            }
        }
    }
}

ToDoList/ToDoList.WEB/Views/Purpose/Create.cshtml
@model ToDoList.WEB.Models.PurposeCreateView


<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="nameModalOperation" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit iformation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="createPurposeForm">
                    @using (Html.BeginForm())
                    {
                        <label id="serverError"></label>
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(p => p.PurposeId)
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(p => p.Name)
                            @Html.TextBoxFor(p => p.Name, new { @class = "form-control", @type = "text", @placeholder = "Enter name" })
                            @Html.ValidationMessageFor(p => p.Name)
                        </div>
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(p => p.Description)
                            @Html.TextBoxFor(p => p.Description, new { @class = "form-control", @type = "text", @placeholder = "Enter description" })
                            @Html.ValidationMessageFor(p => p.Description)
                        </div>
                        <div class="modal-footer">
                            <input id="createPurposeBtn" type="submit" class="btn btn-success" value="Create" />
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(() => {
        showPurposeCreate();
    })

    function showPurposeCreate() {
        $('#myModal').modal('show');
    }

    function hidePurposeCreate() {
        $('#myModal').modal('hide');
    }

    $('form').on('submit', function (event) {
        event.preventDefault();

        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "Purpose")',
            data: $('form').serialize(),
            success: function (result) {
                if (result.result) {
                    hidePurposeCreate();
                    load();
                }
                else {
                    alert('Невозможно добавить цель!');
                }
            }
        })
    })

</script>

ToDoList/ToDoList.WEB/Views/Purpose/Details.cshtml
@model ToDoList.WEB.Models.PurposeIndexView

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="nameModalOperation" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Information about purpose</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3><b>Name</b> : @Model.Name</h3>
                <h3><b>Descroption</b> : @Model.Description</h3>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-primary" onclick="return EditPurpose(@Model.PurposeId)">Edit</a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#myModal').ready(() => {
        showDetailsForm();
    });
    function showDetailsForm() {
        $('#myModal').modal('show');
    }
</script>

ToDoList/ToDoList.WEB/Views/Purpose/Edit.cshtml
@model ToDoList.WEB.Models.PurposeEditView

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="nameModalOperation" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit iformation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="editPurposeForm">
                    @using (Html.BeginForm())
                    {
                        <label id="serverError"></label>
                        @Html.ValidationSummary(true)
                        @Html.HiddenFor(p => p.PurposeId)
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(p => p.Name)
                            @Html.TextBoxFor(p => p.Name, new { @class = "form-control", @type = "text", @placeholder = "Enter name" })
                            @Html.ValidationMessageFor(p => p.Name)
                        </div>
                        <div class="form-group" id="editeForm">
                            @Html.LabelFor(p => p.Description)
                            @Html.TextBoxFor(p => p.Description, new { @class = "form-control", @type = "text", @placeholder = "Enter description" })
                            @Html.ValidationMessageFor(p => p.Description)
                        </div>
                        <div class="modal-footer">
                            <a href="#" class="btn btn-secondary" onclick="return DeletePurpose(@Model.PurposeId)">Delete</a>
                            <input id="editePurposeBtn" type="submit" class="btn btn-success" value="Update" />
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#myModal').ready(() => {
        showPurposeEdit();
    })

    function showPurposeEdit() {
        $('#myModal').modal('show');
    }

    function hidePurposeEdit() {
        $('#myModal').modal('hide');
    }

    function DeletePurpose(id) {

        $.ajax({
            url: '@Url.Action("Delete", "Purpose")/' + id,
            type: "POST",
            success: function (result) {
                if (result.result) {
                    hidePurposeEdit();
                    load();
                }
                else {
                    alert("Нельзя удалить!");
                }
            }
        })
    }

    $('form').on('submit', function (event) {
        event.preventDefault();

        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "Purpose")',
            data: $('form').serialize(),
            success: function (result) {
                if (result.result) {
                    hidePurposeEdit();
                    DetailPurpose(@Model.PurposeId);
                }
                else {
                    alert("Невозможно обновить данные!");
                }
            }
        })
    })
</script>

ToDoList/ToDoList.WEB/Views/Purpose/Index.cshtml
@{
    ViewBag.Title = "Purpose";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Информация о целях</h2>

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="spinner-border" role="status" id="loader">
            <span class="visually-hidden">Загрузка...</span>
        </div>
    </div>
</div>

<div id="lines">
    <div id="window"></div>
    <div id="windowModal"></div>
</div>

<script type="text/javascript">
    jQuery(function() {
        load();
    });

    function load() {
        $('#loader').css('display', 'display');
        console.log("aaaa");
        $('#window').load('@Url.Action("Load", "Purpose")',
            function () {
                $('#loader').css('display', 'none');
            });
    }

    DetailPurpose = function (id) {
        $('#windowModal').load('@Url.Action("Details", "Purpose")/' + id);
    }

    EditPurpose = function (id) {
        $('#windowModal').load('@Url.Action("Edit", "Purpose")/' + id);
    }

    CreatePurpose = function () {
        $('#windowModal').load('@Url.Action("Create", "Purpose")');
    }
</script>

ToDoList/ToDoList.WEB/Views/Purpose/Load.cshtml
@model IEnumerable<ToDoList.WEB.Models.PurposeIndexView>

<a href="#" class="btn btn-outline-primary" onclick="return CreatePurpose()">Create new</a>

@if (Model.Count() > 0)
{
    <table class="table table-bordered border-primary">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th>Function</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.PurposeId</th>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                            <h6><a href="#" class="btn btn-outline-info" onclick="return DetailPurpose(@item.PurposeId)">Detail</a></h6> |
                            <h6><a href="#" class="btn btn-outline-info" onclick="return EditPurpose(@item.PurposeId)">Edit</a></h6>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}